[package]
authors = ["Sean Cross <sean@xobs.io>"]
description = "Core kernel for Xous, including task switching and memory management"
license = "MIT OR Apache-2.0"
edition = "2018"
name = "xous-kernel"
version = "0.9.26"
resolver = "2"

# Dependency versions enforced by Cargo.lock.
[dependencies]
bitflags = "1.2.1"
stats_alloc = { version = "0.1.8", optional = true }
xous-kernel = { package = "xous", path = "../xous-rs", features = [
    "forget-memory-messages",
] }
utralib = { path = "../utralib", optional = true, default_features = false }
rand_chacha = { version = "0.3.1", default_features = false }

[target.'cfg(any(windows,unix))'.dev-dependencies]
xous-kernel = { package = "xous", path = "../xous-rs", features = [
    "forget-memory-messages",
    "processes-as-threads",
] }

[target.'cfg(target_arch = "riscv32")'.dependencies]
riscv = { version = "0.5.6", package = "xous-riscv" }

[features]
cramium-soc = ["utralib/cramium-soc"]
cramium-fpga = ["utralib/cramium-fpga"]
precursor = ["utralib/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode"]

debug-print = []
gdb-stub = []
print-panics = []
report-memory = ["stats_alloc"]
wrap-print = []
v2p = ["xous-kernel/v2p"]
hwsim = []
# default = ["print-panics", "debug-print", "wrap-print"]
default = ["print-panics"]

[target.'cfg(any(windows, unix))'.dependencies]
crossbeam-channel = "0.5"
hex = "0.4"
lazy_static = "1.4"
rand = "0.7.3"
rand_chacha = "0.3.1"